# compose file version
version: '3'

# docker service
services:
  web:
    build: .
    command: sh -c "uvicorn main:app --host=0.0.0.0 --port=8000"
    env_file: 
      - .env.production
    ports:
      - 8000:8000