# compose file version
version: '3'

# docker service
services:
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --host=0.0.0.0 --port=8000"
    env_file: 
      - .env.development
    ports:
      - 8000:8000
    # reload support
    volumes:
      - .:/app